# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0002_title_titleuser'),
        ('stash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stash',
            name='stashTitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='title.Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stash',
            name='stashUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
