# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:55
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmarkForPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('profile1', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='practice.PostProfile')),
                ('text1', models.TextField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('profile2', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='practice.PostProfile')),
                ('text2', models.TextField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='bookmarkforposts',
            name='what_bookmarked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PostProfile'),
        ),
        migrations.AddField(
            model_name='bookmarkforposts',
            name='who_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.UserProfile'),
        ),
    ]
