# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='profile1',
        ),
        migrations.RemoveField(
            model_name='post2',
            name='profile2',
        ),
        migrations.AddField(
            model_name='post1',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post2',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postprofile',
            name='post1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Post1'),
        ),
        migrations.AddField(
            model_name='postprofile',
            name='post2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Post2'),
        ),
    ]
