# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stash', '0001_initial'),
        ('post', '0001_initial'),
        ('comment', '0001_initial'),
        ('title', '0001_initial'),
        ('basic', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('allowUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('postprofileCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('postprofileUpdatedAt', models.DateTimeField(auto_now=True)),
                ('basic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Basic')),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('stash', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stash.Stash')),
                ('title', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='title.Title')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userprofileImage', models.ImageField(upload_to='')),
                ('userprofileDescription', models.TextField(max_length=100)),
                ('userprofileCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('userprofileUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wdt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdtCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('wdtUpdatedAt', models.DateTimeField(auto_now=True)),
                ('wdtContents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.PostProfile')),
                ('wdtUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='allow',
            name='allowedUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowedUserProfile', to='info.UserProfile'),
        ),
        migrations.AddField(
            model_name='allow',
            name='allowingUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowingUserProfile', to='info.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='wdt',
            unique_together=set([('wdtUser', 'wdtContents')]),
        ),
        migrations.AlterUniqueTogether(
            name='allow',
            unique_together=set([('allowingUserProfile', 'allowedUserProfile')]),
        ),
    ]
