# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostProfile',
            new_name='Contentsprofile',
        ),
        migrations.AlterField(
            model_name='allow',
            name='allowedUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowedUserProfile', to='info.Userprofile'),
        ),
        migrations.AlterField(
            model_name='allow',
            name='allowingUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowingUserProfile', to='info.Userprofile'),
        ),
        migrations.AlterField(
            model_name='wdt',
            name='wdtUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Userprofile'),
        ),
    ]
