# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20170328_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allow',
            name='allowedUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowedUserProfile', to='info.Userprofile'),
        ),
        migrations.AlterField(
            model_name='allow',
            name='allowingUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowingUserProfile', to='info.Userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userprofileImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wdt',
            name='wdtUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Userprofile'),
        ),
    ]
