# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20170328_0424'),
        ('stash', '0002_auto_20170328_0424'),
        ('basic', '0002_auto_20170328_0424'),
        ('title', '0002_title_titleuser'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentBasic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Basic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentStash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stash.Stash'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='title.Title'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentUpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
