# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20170328_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentTitle',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentBasic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Basic'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentStash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stash.Stash'),
        ),
    ]
